#!/bin/sh

echo ""
echo "Checkm4te! ♕"
echo ""
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo ""
echo "Thank You For Installing deCard v2.2.0"
echo ""
echo "Created by AppleWorm ♤"
